python wiki.py https://en.wikipedia.org/wiki/Leicester_City_F.C. 7 && echo 1
python wiki.py https://en.wikipedia.org/wiki/Arsenal_F.C. 2 && echo 2
python wiki.py https://en.wikipedia.org/wiki/Tottenham_Hotspur_F.C. 17 && echo 3
python wiki.py https://en.wikipedia.org/wiki/Manchester_City_F.C. 9 && echo 4
python wiki.py https://en.wikipedia.org/wiki/Manchester_United_F.C. 10 && echo 5
python wiki.py https://en.wikipedia.org/wiki/Southampton_F.C. 13 && echo 6
python wiki.py https://en.wikipedia.org/wiki/West_Ham_United_F.C. 20 && echo 7
python wiki.py https://en.wikipedia.org/wiki/Liverpool_F.C. 8 && echo 8
python wiki.py https://en.wikipedia.org/wiki/Stoke_City_F.C. 14 && echo 9
python wiki.py https://en.wikipedia.org/wiki/Chelsea_F.C. 4 && echo 10
python wiki.py https://en.wikipedia.org/wiki/Everton_F.C. 6 && echo 11
python wiki.py https://en.wikipedia.org/wiki/Swansea_City_A.F.C. 16 && echo 12
python wiki.py https://en.wikipedia.org/wiki/Watford_F.C. 18 && echo 13
python wiki.py https://en.wikipedia.org/wiki/West_Bromwich_Albion_F.C. 19 && echo 14
python wiki.py https://en.wikipedia.org/wiki/Crystal_Palace_F.C. 5 && echo 15
python wiki.py https://en.wikipedia.org/wiki/A.F.C._Bournemouth 1 && echo 16
python wiki.py https://en.wikipedia.org/wiki/Sunderland_A.F.C. 15 && echo 17
python wiki.py https://en.wikipedia.org/wiki/Newcastle_United_F.C. 11 && echo 18
python wiki.py https://en.wikipedia.org/wiki/Norwich_City_F.C. 12 && echo 19
python wiki.py https://en.wikipedia.org/wiki/Aston_Villa_F.C. 3 && echo 20
python wiki.py https://en.wikipedia.org/wiki/Real_Madrid_C.F. 21 && echo 21
python wiki.py https://en.wikipedia.org/wiki/FC_Barcelona 22 && echo 22
python wiki.py https://en.wikipedia.org/wiki/Juventus_F.C. 31 && echo 23
